In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [3]:
df = pd.read_csv("C:/dsbda/Social_Media_Advertising.csv")

In [4]:
df.head()

,Campaign_ID,Target_Audience,Campaign_Goal,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date,Company
0,529013,Men 35-44,Product Launch,15 Days,Instagram,0.15,$500.00,5.790000,Las Vegas,Spanish,500,3000,7,Health,2022-02-25,Aura Align
1,275352,Women 45-60,Market Expansion,15 Days,Facebook,0.01,$500.00,7.210000,Los Angeles,French,500,3000,5,Home,2022-05-12,Hearth Harmony
2,692322,Men 45-60,Product Launch,15 Days,Instagram,0.08,$500.00,0.430000,Austin,Spanish,500,3000,9,Technology,2022-06-19,Cyber Circuit
3,675757,Men 25-34,Increase Sales,15 Days,Pinterest,0.03,$500.00,0.909824,Miami,Spanish,293,1937,1,Health,2022-09-08,Well Wish
4,535900,Men 45-60,Market Expansion,15 Days,Pinterest,0.13,$500.00,1.422828,Austin,French,293,1937,1,Home,2022-08-24,Hearth Harmony

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       300000 non-null  int64
 1   Target_Audience   300000 non-null  object
 2   Campaign_Goal     300000 non-null  object
 3   Duration          300000 non-null  object
 4   Channel_Used      300000 non-null  object
 5   Conversion_Rate   300000 non-null  float64
 6   Acquisition_Cost  300000 non-null  object
 7   ROI               300000 non-null  float64
 8   Location          300000 non-null  object
 9   Language          300000 non-null  object
 10  Clicks            300000 non-null  int64
 11  Impressions       300000 non-null  int64
 12  Engagement_Score  300000 non-null  int64
 13  Customer_Segment  300000 non-null  object
 14  Date              300000 non-null  object
 15  Company           300000 non-null  object
dtypes: float64(2), int64(4), object(10)
memory usage: 36.6+ MB

In [6]:
df.shape

(300000, 16)

In [7]:
df.describe()

,Campaign_ID,Conversion_Rate,ROI,Clicks,Impressions,Engagement_Score
count,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000
mean,550444.804487,0.080009,3.177691,18153.670370,56034.236387,4.369217
std,260252.586037,0.040563,2.461200,11027.023294,32583.136334,3.156492
min,100001.000000,0.010000,0.000000,293.000000,1937.000000,1.000000
25%,325003.500000,0.050000,0.930000,8821.000000,28362.000000,1.000000
50%,551164.500000,0.080000,2.670000,17230.000000,54098.000000,4.000000
75%,776284.500000,0.110000,5.330000,26808.000000,80925.250000,7.000000
max,999998.000000,0.150000,8.000000,40000.000000,120000.000000,10.000000

In [8]:
df['Acquisition_Cost'].unique()[:10]

array(['$500.00', '$500.10', '$500.18', '$500.20', '$500.27', '$500.45',
       '$500.49', '$500.59', '$500.61', '$500.66'], dtype=object)

In [9]:
df['Acquisition_Cost'] = df['Acquisition_Cost'].str.replace('$','')
df['Acquisition_Cost'] = df['Acquisition_Cost'].astype(float)

In [10]:
df['Date'] = pd.to_datetime(df['Date'])

In [11]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [12]:
df.drop('Date', axis=1, inplace=True)

In [13]:
df.isnull().sum()

Campaign_ID         0
Target_Audience     0
Campaign_Goal       0
Duration            0
Channel_Used        0
Conversion_Rate     0
Acquisition_Cost    0
ROI                 0
Location            0
Language            0
Clicks              0
Impressions         0
Engagement_Score    0
Customer_Segment    0
Company             0
Year                0
Month               0
Day                 0
dtype: int64

In [14]:
df = df.dropna()

In [16]:
df.cov(numeric_only=True)

,Campaign_ID,Conversion_Rate,Acquisition_Cost,ROI,Clicks,Impressions,Engagement_Score,Year,Month,Day
Campaign_ID,6.773141e+10,-8.028774,3.752297e+06,310.476673,8.342850e+06,2.537627e+07,1546.821723,0.0,-3702.457196,-2159.052210
Conversion_Rate,-8.028774e+00,0.001645,3.621771e-01,-0.000025,9.149637e-01,2.714239e+00,-0.000255,0.0,-0.000002,-0.000286
Acquisition_Cost,3.752297e+06,0.362177,1.849890e+07,-17.559880,4.390926e+07,1.322011e+08,-37.093338,0.0,-50.385243,105.546547
ROI,3.104767e+02,-0.000025,-1.755988e+01,6.057507,5.111572e+03,1.331288e+04,2.755712,0.0,0.010203,-0.007885
Clicks,8.342850e+06,0.914964,4.390926e+07,5111.571665,1.215952e+08,3.588526e+08,6964.658477,0.0,-75.365680,199.742542
Impressions,2.537627e+07,2.714239,1.322011e+08,13312.876124,3.588526e+08,1.061661e+09,18127.385540,0.0,-244.268804,624.280609
Engagement_Score,1.546822e+03,-0.000255,-3.709334e+01,2.755712,6.964658e+03,1.812739e+04,9.963442,0.0,0.011373,-0.060062
Year,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.0,0.000000,0.000000
Month,-3.702457e+03,-0.000002,-5.038524e+01,0.010203,-7.536568e+01,-2.442688e+02,0.011373,0.0,11.891709,0.213071
Day,-2.159052e+03,-0.000286,1.055465e+02,-0.007885,1.997425e+02,6.242806e+02,-0.060062,0.0,0.213071,77.425692

In [18]:
df['Success'] = np.where(df['ROI'] > 3, 1, 0)

In [19]:
X = df.drop('Success', axis=1)
Y = df['Success']

In [20]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.2, random_state=42)

In [22]:
df.drop('Campaign_ID', axis=1, inplace=True)

In [23]:
df['Success'] = np.where(df['ROI'] > 3, 1, 0)

In [24]:
X = df.drop('Success', axis=1)
Y = df['Success']

In [25]:
X = pd.get_dummies(X, drop_first=True)

In [26]:
X.dtypes

Conversion_Rate           float64
Acquisition_Cost          float64
ROI                       float64
Clicks                      int64
Impressions                 int64
                           ...
Company_Vigor Valley         bool
Company_Vital Vigor          bool
Company_Vogue Visions        bool
Company_Well Wish            bool
Company_Wellness Waves       bool
Length: 85, dtype: object

In [27]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [28]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [29]:
logreg = LogisticRegression()
logreg.fit(xtrain, ytrain)

LogisticRegression()

In [30]:
y_pred = logreg.predict(xtest)

In [31]:
y_train_pred = logreg.predict(xtrain)

In [32]:
cm = confusion_matrix(ytest, y_pred)
print(cm)

[[31779     9]
 [   18 28194]]

In [33]:
accuracy_score(ytest, y_pred)

0.99955

In [34]:
precision_score(ytest, y_pred)

0.9996808850122327

In [35]:
recall_score(ytest, y_pred)

0.9993619736282433

In [36]:
print("Confusion Matrix:\n", confusion_matrix(ytest, y_pred))
print("Accuracy:", accuracy_score(ytest, y_pred))
print("Precision:", precision_score(ytest, y_pred))
print("Recall:", recall_score(ytest, y_pred))

Confusion Matrix:
 [[31779     9]
 [   18 28194]]
Accuracy: 0.99955
Precision: 0.9996808850122327
Recall: 0.9993619736282433